export const NOTIFICATION_TYPES = {
  FRIEND_REQUEST: "FRIEND_REQUEST",
  FRIEND_REQUEST_ACCEPTED: "FRIEND_REQUEST_ACCEPTED",
  FRIEND_REQUEST_DECLINED: "FRIEND_REQUEST_DECLINED",
  FRIEND_REQUEST_DELETED: "FRIEND_REQUEST_DELETED",
  NEW_MESSAGE: "NEW_MESSAGE",
  MENTION: "MENTION",
  MESSAGE_REACTION: "MESSAGE_REACTION",
  GROUP_INVITE: "GROUP_INVITE",
};
